### ISSUE TITLE
Show last post on top

### ISSUE THREAD

**Issue by ghost** [mitchellurgero/simpleblog#3]
Is it possible to have the last post show on top of the main blog page? Currently, the last post shows on bottom. Thanks.

Also, is there a limit to how many blog entries show up on the main page?

**Comment by mitchellurgero** [comment]
For the first question, yes, you can invert the array that is displayed in the code.

For the second question, there is no limit. This is just an example application and technically should not be used as an actual blog system. It was made to simply demonstrate the power and flexibility of my JSONDatabase class in another repo. Feel free to continue using it if you like, but it is not recommended.

Edit:

For the inverted array for post display change line 47 from:
`$posts = array_reverse($db->select("posts"));`

to:
`$posts = $db->select("posts");`

**Comment by ghost** [comment]
cool, thanks!!!!!!!!
